### ISSUE TITLE
Lab 5, ex. 1 Graph database needs partition key

### ISSUE THREAD

**Issue by trayhumphrey** [MicrosoftLearning/20777A---Implementing-Microsoft-Azure-Cosmos-DB-Solutions#13]
In Lab 5, ex. 1, a Cosmos DB graph is created. Azure now requires a partition key for a new Cosmos DB database or graph. The lab is missing that new requirement. 

I found a workaround and students used it to complete the lab. It is described below.
* Ex. 1, Task 1: Specify a partition key when creating the graph. I used /partkey.
* Ex. 1, Task 2: Edit purchase-history.json and add the /partkey property to each item. Then specify /partkey when uploading JSON file through dtui.
* Ex. 2, Task 2: In Recommendations class, all 3 instances of addV and addE need the new property specified:
  ...addV('product').property('partkey','partkey')…

Overall, a great repo! The labs are long, but they work! I feel they really show some great examples of using Cosmos DB in larger, more realistic applications. Thanks for that!

**Comment by AndyFogg** [comment]
Thank you for your comment. We are investigating the issue and will reply as soon as possible.

**Comment by JohnPWSharp** [comment]
I have addressed these issues. Lab 5 now uses a partitioned graph.
