### ISSUE TITLE
Module 3 LAK Ex 4 Task 4

### ISSUE THREAD

**Issue by XtremeLabsSupport** [MicrosoftLearning/20777A---Implementing-Microsoft-Azure-Cosmos-DB-Solutions#2]
Step 5 is no longer needed. Step 6 seems to be the correct version of the if statement. Skipping over step 5 allows to solution to build properly.

**Comment by JohnPWSharp** [comment]
(Author) Step 5 is definitely required, otherwise the code does not call the stored procedure.

**Comment by JohnPWSharp** [comment]
Just to confirm, both steps are required. However, step 5 updates code in the method **CancelOrderAsyn** whereas step 6 updates the method **CancelBackorderAsync** (different methods). Unfortunately, the **TODO** comment is the same in both methods. I have clarified the lab and LAK docs to highlight that these steps refer to different methods.
